spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/person_springboot?useTimezone=true&serverTimezone=UTC
    username: root
    password: securitypro
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

server:
  port: 8080

springdoc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true
